repos:
  - repo: local
    hooks:
      - id: tfsec
        name: tfsec security scan
        entry: bash
        args:
          - -c
          - 'docker run --rm -v "$(pwd):/data" aquasec/tfsec /data'
        language: system
        pass_filenames: false
        files: \.tf$


  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      # - id: terraform_validate
      - id: terraform_docs
        exclude: ^examples/.*
        args:
        - --args=--config=.terraform-docs.yml
        - --hook-config=--path-to-file=README.md
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true
      # - id: terraform_tflint
